frontend_slam:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 1.5
    vg_size_for_map: 0.075
    set_initial_pose: false
    use_odom: false
    use_constant_vel: false
    use_imu: false
    debug_flag: false
    tum_log_filename: "/home/ruan/dev_ws/tum_trajectory.txt"
    iteration_log_filename: "/home/ruan/dev_ws/iteration_log.txt"
